#!/bin/bash

# 🔍 VERCEL BUILD FAILURE DIAGNOSIS
# ================================

set -e

echo "🔍 VERCEL BUILD FAILURE DIAGNOSIS"
echo "================================="
echo ""

echo "🚨 Issue: Deployment failed with 'npm run build exited with 1'"
echo "🎯 URL: https://festival-chat-k6a5fbujy-thepeddlers-projects-d74f9d42.vercel.app"
echo ""

echo "📋 STEP 1: Test local build first"
echo "================================="
echo ""
echo "Let's see if the build works locally before debugging Vercel:"
echo ""
echo "npm run build"
echo ""

# Test local build
echo "🧪 Testing local build..."
if npm run build; then
    echo "✅ Local build SUCCESSFUL"
    echo "   → Issue is Vercel-specific (environment, dependencies, etc.)"
    echo ""
else
    echo "❌ Local build FAILED"
    echo "   → Fix local build first, then redeploy"
    echo ""
    echo "🔧 Quick fixes to try:"
    echo "1. rm -rf node_modules package-lock.json .next"
    echo "2. npm install"
    echo "3. npm run build"
    echo ""
    exit 1
fi

echo "📋 STEP 2: Common Vercel build issues"
echo "===================================="
echo ""
echo "Since local build works, check these Vercel-specific issues:"
echo ""
echo "1. 🔧 ENVIRONMENT VARIABLES:"
echo "   - Go to: https://vercel.com/dashboard"
echo "   - Project Settings → Environment Variables"
echo "   - Verify all NEXT_PUBLIC_* variables are set for Production"
echo ""
echo "2. 🔧 NODE.JS VERSION:"
echo "   - Vercel uses Node.js 18+ by default"
echo "   - Check if your local Node version matches"
echo "   - Current local version: $(node --version)"
echo ""
echo "3. 🔧 DEPENDENCIES:"
echo "   - Ensure all dependencies are in 'dependencies', not 'devDependencies'"
echo "   - Check for React 19 / Next.js 15 compatibility issues"
echo ""
echo "4. 🔧 BUILD COMMAND:"
echo "   - Vercel should use: npm run build"
echo "   - Check Project Settings → Build & Development Settings"
echo ""

echo "📋 STEP 3: Get detailed Vercel logs"
echo "=================================="
echo ""
echo "🔍 Method 1: Vercel Dashboard"
echo "   1. Go to: https://vercel.com/dashboard"
echo "   2. Find your festival-chat project"
echo "   3. Click on the failed deployment"
echo "   4. Look at the 'Building' section for red error messages"
echo ""
echo "🔍 Method 2: Alternative log command"
echo "   vercel --debug"
echo ""
echo "🔍 Method 3: Check deployment status"
echo "   vercel list"
echo ""

echo "📋 STEP 4: Quick fixes to try"
echo "============================="
echo ""
echo "🚀 Quick Fix 1: Force clean build"
echo "   vercel --force"
echo ""
echo "🚀 Quick Fix 2: Disable TypeScript/ESLint temporarily"
echo "   Add to next.config.ts:"
echo "   typescript: { ignoreBuildErrors: true },"
echo "   eslint: { ignoreDuringBuilds: true },"
echo ""
echo "🚀 Quick Fix 3: Set build command with more memory"
echo "   In Vercel Project Settings → Build Command:"
echo "   NODE_OPTIONS='--max-old-space-size=4096' npm run build"
echo ""

echo "📋 STEP 5: Emergency deployment"
echo "==============================="
echo ""
echo "If you need to deploy immediately:"
echo ""
echo "1. 🎭 Try staging first:"
echo "   npm run staging:vercel:complete"
echo "   (This might work if it's a production-specific issue)"
echo ""
echo "2. 🔧 Simplify the build:"
echo "   - Comment out complex imports"
echo "   - Disable admin dashboard temporarily"
echo "   - Remove WebSocket server deployment"
echo ""

echo "🎯 NEXT STEPS:"
echo "============="
echo ""
echo "1. Run 'npm run build' locally first"
echo "2. If local works, check Vercel environment variables"
echo "3. If local fails, fix the build error shown above"
echo "4. Try 'vercel --force' for a clean rebuild"
echo ""
echo "💡 Most likely cause: Missing environment variable or dependency issue"
