#!/bin/bash

# 🎯 PRODUCTION VS PREVIEW ENVIRONMENT ISSUE
# ==========================================

set -e

echo "🎯 PRODUCTION VS PREVIEW ENVIRONMENT ISSUE DETECTED"
echo "=================================================="
echo ""

echo "✅ GOOD NEWS: Preview deployments are working!"
echo "❌ ISSUE: Production deployments are failing!"
echo ""
echo "This means the code is fine, but there's an environment-specific issue."
echo ""

echo "🔍 ANALYSIS FROM VERCEL LIST:"
echo "============================="
echo "✅ Working: https://festival-chat-ampz5sqdg-thepeddlers-projects-d74f9d42.vercel.app (Preview)"
echo "❌ Failing: https://festival-chat-k6a5fbujy-thepeddlers-projects-d74f9d42.vercel.app (Production)"
echo ""

echo "🎯 MOST LIKELY CAUSE: Missing Production Environment Variables"
echo "============================================================="
echo ""
echo "Preview has the staging environment variables, but Production is missing them!"
echo ""

echo "🔧 IMMEDIATE FIX:"
echo "================"
echo ""
echo "1. 🌐 Go to Vercel Dashboard:"
echo "   https://vercel.com/dashboard"
echo ""
echo "2. 📁 Find your 'festival-chat' project"
echo ""
echo "3. ⚙️ Go to Settings → Environment Variables"
echo ""
echo "4. 🔍 Check if these variables exist for PRODUCTION:"
echo "   - NEXT_PUBLIC_SIGNALING_SERVER"
echo "   - BUILD_TARGET"
echo "   - NODE_ENV"
echo "   - PLATFORM"
echo ""
echo "5. ➕ If missing, add them for Production environment:"
echo ""
echo "   NEXT_PUBLIC_SIGNALING_SERVER = wss://peddlenet-websocket-server-hfttiarlja-uc.a.run.app"
echo "   BUILD_TARGET = production"  
echo "   NODE_ENV = production"
echo "   PLATFORM = vercel"
echo ""

echo "🚀 ALTERNATIVE QUICK FIX:"
echo "========================="
echo ""
echo "Since Preview works, let's test the working preview URL:"
echo ""
echo "1. 🧪 Test the working preview:"
echo "   https://festival-chat-ampz5sqdg-thepeddlers-projects-d74f9d42.vercel.app"
echo ""
echo "2. 📊 Check admin dashboard:"
echo "   https://festival-chat-ampz5sqdg-thepeddlers-projects-d74f9d42.vercel.app/admin-analytics"
echo ""
echo "3. 🔍 Verify environment detection:"
echo "   - Should show 'STAGING' (yellow)"
echo "   - Should show 'vercel-preview' platform"
echo ""

echo "📋 STEP-BY-STEP FIX:"
echo "==================="
echo ""
echo "Step 1: Test working preview"
echo "  → Open working preview URL above"
echo "  → Confirm it works correctly"
echo ""
echo "Step 2: Copy environment variables"
echo "  → Go to Vercel Dashboard → Settings → Environment Variables"
echo "  → Copy all Preview variables to Production"
echo "  → Change values to production equivalents"
echo ""
echo "Step 3: Redeploy production"
echo "  → vercel --prod --force"
echo ""

echo "🎉 EXPECTED RESULT:"
echo "=================="
echo ""
echo "After setting production environment variables:"
echo "✅ Production deployment will work"
echo "✅ https://peddlenet.app will be accessible"
echo "✅ Admin dashboard will show 'PRODUCTION' (red)"
echo ""
echo "The preview already works, so this is definitely an environment variable issue!"
