steps:
  # Simple Docker build for production deployment - CACHE BUSTING VERSION
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.minimal', '--build-arg', 'BUILD_DATE=${BUILD_ID}', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}', '.']

  # Push the image  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}']

  # Deploy to Cloud Run (PRODUCTION)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--port'
      - '8080'
      - '--set-env-vars'
      - 'NODE_ENV=production,BUILD_TARGET=production,PLATFORM=cloudrun'

# Default substitutions
substitutions:
  _SERVICE_NAME: 'peddlenet-websocket-server'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'

options:
  logging: CLOUD_LOGGING_ONLY
