# Railway deployment configuration for signaling server
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node signaling-server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PORT = 3001
NODE_ENV = "production"
