name: 🔥 Firebase Preview Channel Deploy

on:
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
    inputs:
      preview_name:
        description: 'Custom preview channel name (optional)'
        required: false
        default: ''

env:
  NODE_VERSION: '18'
  FIREBASE_PROJECT_ID: 'festival-chat-peddlenet'

jobs:
  preview-deploy:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    
    outputs:
      preview-url: ${{ steps.deploy.outputs.details_url }}
      channel-id: ${{ steps.deploy.outputs.channel_id }}
    
    steps:
      - name: 🛎️ Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🟢 Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 📦 Install Dependencies
        run: |
          npm ci
          echo "✅ Dependencies installed successfully"

      - name: 🔍 Verify Project Structure
        run: |
          echo "📁 Project structure:"
          ls -la
          echo "📄 Package.json scripts:"
          npm run --silent
          echo "🔥 Firebase config:"
          ls -la .firebase* 2>/dev/null || echo "No Firebase config files found"

      - name: 🏗️ Build for Firebase
        run: |
          echo "🏗️ Building project for Firebase deployment..."
          npm run build:firebase
          echo "✅ Build completed successfully"
        env:
          NEXT_PUBLIC_SIGNALING_SERVER: ${{ secrets.FIREBASE_SIGNALING_SERVER_URL }}
          NEXT_PUBLIC_DETECTED_IP: 'firebase-preview'

      - name: 🔧 Verify Build Output
        run: |
          echo "📁 Build output structure:"
          ls -la out/ 2>/dev/null || echo "No 'out' directory found"
          ls -la .next/ 2>/dev/null || echo "No '.next' directory found"
          ls -la build/ 2>/dev/null || echo "No 'build' directory found"

      - name: 🚀 Deploy to Firebase Preview Channel
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FESTIVAL_CHAT }}
          projectId: ${{ env.FIREBASE_PROJECT_ID }}
          channelId: ${{ github.event.inputs.preview_name || format('pr-{0}', github.event.number) }}
          expires: 7d
          target: festival-chat-peddlenet
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: 🎉 Preview Deployment Success
        run: |
          echo "🎉 Preview deployment successful!"
          echo "🔗 Preview URL: ${{ steps.deploy.outputs.details_url }}"
          echo "📋 Channel ID: ${{ steps.deploy.outputs.channel_id }}"
          echo "⏰ Expires: 7 days from now"

      - name: 💬 Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = '${{ steps.deploy.outputs.details_url }}';
            const channelId = '${{ steps.deploy.outputs.channel_id }}';
            
            const comment = `## 🎪 Festival Chat Preview Ready!
            
            Your preview deployment is ready for testing:
            
            ### 🔗 Links
            - **Preview URL**: ${previewUrl}
            - **Channel ID**: \`${channelId}\`
            - **Expires**: 7 days from now
            
            ### 📱 Testing Checklist
            - [ ] Desktop browser functionality
            - [ ] Mobile browser (iPhone Safari, Android Chrome)
            - [ ] QR code generation and scanning
            - [ ] Cross-room notifications
            - [ ] Room navigation and switching
            - [ ] Connection stability
            
            ### 🛠️ Development Commands
            \`\`\`bash
            # Quick iteration
            npm run deploy:firebase:super-quick
            
            # Standard deployment
            npm run deploy:firebase:quick
            
            # Full infrastructure update
            npm run deploy:firebase:complete
            \`\`\`
            
            ---
            
            *Preview will auto-delete in 7 days. Subsequent pushes to this PR will update the same preview channel.*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  cleanup-old-previews:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    
    steps:
      - name: 🛎️ Checkout Repository
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 📦 Install Firebase CLI
        run: npm install -g firebase-tools

      - name: 🧹 Cleanup Preview Channel
        run: |
          echo "🧹 Cleaning up preview channel for PR #${{ github.event.number }}"
          firebase hosting:channel:delete pr-${{ github.event.number }} --project ${{ env.FIREBASE_PROJECT_ID }} --force || echo "Channel may not exist"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
